export type Lang = 'ja' | 'en'

export const dict = {
  ja: {
    nav: { home: 'ホーム', shop: 'ショップ' },
    hero: {
      eyebrow: '冷凍肉卸売業者',
      title1: '冷凍肉',
      title2: '大量仕入れ',
      title3: '安定供給',
      subtitle: 'レストラン、ホテル、食品事業者向けの信頼できる冷凍肉供給。一貫した品質、競争力のある大口価格、確かなコールドチェーン配送。',
      cta: '商品カタログを見る',
      marquee: ['冷凍', '大口注文', 'B2B', '卸売', '牛肉', '豚肉', '鶏肉', '冷凍供給', '信頼性', 'バルクカット', 'コールドチェーン', 'OISHI NIKU'],
    },
    home: {
      featuredEyebrow: '商品ラインナップ',
      featuredTitle: '取扱商品',
      featuredViewAll: 'すべて見る',
      featuredEmpty: 'おすすめ商品はまだありません',
      featuredEmptyDesc: '管理画面から商品を追加し、おすすめに設定してください。',
      featuredViewAllBtn: 'すべての商品を見る',
      faqEyebrow: '取引に関するお問い合わせ',
      faqTitle: 'よくある質問',
      b2bEyebrow: 'パートナーになる',
      b2bTitle: '取引口座を開設する',
      b2bDesc: 'レストラン、ホテル、食品卸業者の方へ — 卸売価格、NET-30 支払条件、専任アカウントマネージャーをご利用いただけます。',
      b2bPlaceholder: 'ビジネスメールアドレスを入力',
      b2bCta: '今すぐ申し込む',
      faqs: [
        { q: '最小注文数量はどのくらいですか？', a: '1商品あたり最小20kgからご注文いただけます。混載パレットの場合、最小注文合計は100kgです。200kg、500kg、1000kgの各基準で数量割引が自動適用されます。' },
        { q: '冷凍肉の梁包・配送方法は？', a: '全商品は真空パックの上、ドライアイス入りの断熱カートンで梁包されます。倉庫からお届け先まで完全なコールドチェーンを維持し、製品温度が-18℃を超えることはありません。' },
        { q: '商品はどのような認証を取得していますか？', a: 'サプライチェーン全体がHACCP認証を取得しており、全商品が国際食品安全基準を満たしています。ご要望に応じて、完全なトレーサビリティ証明書、ハラール認証、原産国証明書を提供できます。' },
        { q: 'レストランやホテル向けのカスタムカットは対応可能ですか？', a: 'はい。定期注文のB2Bクライアント様には、カスタムポーション加工、トリミング、ラベリングに対応しています。仕様要件についてはお気軽にお問い合わせください。' },
        { q: '支払い・クレジット条件はどうなっていますか？', a: '銀行振込をお受けしており、承認済み法人口座にはNET-30の支払い条件を提供しています。初回注文は前払いが必要です。取引口座の開設については営業チームまでお問い合わせください。' },
      ],
    },
    products: {
      eyebrow: '商品一覧',
      title: '全商品',
      countBefore: '',
      countAfter: '件の商品',
      notFound: '商品が見つかりません',
      notFoundDesc: 'フィルターまたは検索キーワードを変更してください。',
      allCategories: 'すべてのカテゴリー',
      sortNewest: '新着順',
      sortPopular: '人気順',
      sortPriceAsc: '価格: 安い順',
      sortPriceDesc: '価格: 高い順',
    },
    product: {
      grade: 'グレード',
      origin: '産地',
      cutType: '部位',
      weight: '重量',
      per: 'あたり',
      outOfStock: '在庫切れ',
      inStockBefore: '在庫あり（',
      inStockAfter: '点）',
      about: '商品について',
      related: 'こちらもおすすめ',
      addToCart: 'カートに追加',
      badgeColdChain: 'コールドチェーン配送',
      badgeHaccp: 'HACCP認証取得',
      badgeVacuum: '真空パック',
    },
    cart: {
      title: 'カート',
      empty: 'カートは空です',
      shopNow: '今すぐ購入',
      freeShippingBefore: 'あと ',
      freeShippingAfter: ' で送料無料！',
      freeShippingReached: '送料無料の対象です！',
      subtotal: '小計',
      shippingNote: '送料・税金はチェックアウト時に計算されます。',
      checkout: 'お会計',
      continueShopping: 'ショッピングを続ける',
    },
    footer: {
      tagline: '最高品質の農場から厳選した精肉。最良のカットを直接お届けします。',
      shop: 'ショップ',
      allProducts: '全商品',
      wagyu: '和牛',
      pork: '豚肉',
      chicken: '鶏肉',
      lamb: 'ラム肉',
      support: 'サポート',
      shipping: '配送情報',
      returns: '返品・交換',
      faq: 'よくある質問',
      privacy: 'プライバシーポリシー',
      terms: '利用規約',
    },
    checkout: {
      orderComplete: 'ご注文完了！',
      orderNumberPrefix: '注文番号 #',
      thankYou1: 'ご注文ありがとうございます！',
      thankYou2: ' に確認メールをお送りしました。商品は近日中に発送いたします。',
      continueShopping: 'ショッピングを続ける',
      emptyCart: 'カートは空です',
      backToShopping: 'ショッピングに戻る',
      title: 'お会計',
      customerInfo: 'お客様情報',
      name: '氏名 *',
      namePlaceholder: '山田 太郎',
      email: 'メールアドレス *',
      emailPlaceholder: 'taro@example.com',
      phone: '電話番号',
      phonePlaceholder: '090-0000-0000',
      shippingAddress: 'お届け先住所',
      address: '住所 *',
      addressPlaceholder: '東京都渋谷区1-2-3',
      city: '市区町村 *',
      cityPlaceholder: '渋谷区',
      state: '都道府県',
      postal: '郵便番号 *',
      postalPlaceholder: '150-0001',
      country: '国',
      notes: '備考（任意）',
      notesPlaceholder: '特別な指示、希望配達時間など...',
      payment: '支払い方法',
      payCard: 'クレジット / デビットカード',
      payCardDesc: 'カードで安全にお支払い',
      payBank: '銀行振込',
      payBankDesc: '直接口座にお振込みください',
      payCod: '代金引換',
      payCodDesc: '商品到着時にお支払い',
      cardPlaceholder: 'カード決済フォームはこちらに統合されます',
      bankDetailsTitle: '銀行振込の詳細：',
      bankName: '銀行: ファーストナショナル銀行',
      bankAccount: '口座番号: 123-456-7890',
      bankRef: '振込名義: ご注文番号（注文後にお知らせします）',
      errorRequired: '必須項目をすべて入力してください。',
      errorGeneral: 'エラーが発生しました。もう一度お試しください。',
      orderSummary: '注文内容',
      quantityLabel: '数量: ',
      subtotal: '小計',
      shipping: '送料',
      free: '無料',
      tax: '消費税（10%）',
      total: '合計',
      placeOrder: '注文する',
      placing: '注文中...',
      secureBadge: '安全なチェックアウト',
    },
    orders: {
      title: '注文の追跡',
      desc: '注文状況を確認するには、注文番号とご注文時に使用したメールアドレスをお知らせの上、お問い合わせください。',
      contact: 'サポートに連絡する',
      continueShopping: 'ショッピングを続ける',
    },
  },

  en: {
    nav: { home: 'Home', shop: 'Shop' },
    hero: {
      eyebrow: 'Frozen Meat Wholesaler',
      title1: 'Frozen',
      title2: 'Bulk Orders',
      title3: 'Stable Supply',
      subtitle: 'Reliable frozen meat supply for restaurants, hotels, and food businesses. Consistent quality, competitive bulk pricing, and dependable cold chain delivery.',
      cta: 'View Product Catalog',
      marquee: ['Frozen', 'Bulk Orders', 'B2B', 'Wholesale', 'Beef', 'Pork', 'Chicken', 'Cold Supply', 'Reliability', 'Bulk Cuts', 'Cold Chain', 'OISHI NIKU'],
    },
    home: {
      featuredEyebrow: 'Product Lineup',
      featuredTitle: 'Our Products',
      featuredViewAll: 'View All',
      featuredEmpty: 'No featured products yet',
      featuredEmptyDesc: 'Add products from the admin panel and mark them as featured.',
      featuredViewAllBtn: 'View All Products',
      faqEyebrow: 'Business Inquiries',
      faqTitle: 'FAQ',
      b2bEyebrow: 'Become a Partner',
      b2bTitle: 'Open a Trade Account',
      b2bDesc: 'For restaurants, hotels, and food distributors — enjoy wholesale pricing, NET-30 payment terms, and a dedicated account manager.',
      b2bPlaceholder: 'Enter your business email',
      b2bCta: 'Apply Now',
      faqs: [
        { q: 'What is the minimum order quantity?', a: 'Minimum 20kg per product. For mixed pallets, the minimum total order is 100kg. Volume discounts automatically apply at the 200kg, 500kg, and 1000kg thresholds.' },
        { q: 'How is frozen meat packaged and shipped?', a: 'All products are vacuum-packed and packaged in insulated cartons with dry ice. A complete cold chain is maintained from warehouse to delivery, and product temperature never exceeds -18°C.' },
        { q: 'What certifications do your products have?', a: 'Our entire supply chain is HACCP certified and all products meet international food safety standards. Upon request, we can provide full traceability certificates, halal certification, and certificates of origin.' },
        { q: 'Can you provide custom cuts for restaurants and hotels?', a: 'Yes. For B2B clients with regular orders, we offer custom portioning, trimming, and labeling. Please feel free to contact us regarding your specification requirements.' },
        { q: 'What are the payment and credit terms?', a: 'We accept bank transfers and offer NET-30 payment terms for approved corporate accounts. First orders require prepayment. Please contact our sales team to open a trade account.' },
      ],
    },
    products: {
      eyebrow: 'Products',
      title: 'All Products',
      countBefore: '',
      countAfter: ' products',
      notFound: 'No products found',
      notFoundDesc: 'Try changing the filters or search keywords.',
      allCategories: 'All Categories',
      sortNewest: 'Newest',
      sortPopular: 'Popular',
      sortPriceAsc: 'Price: Low to High',
      sortPriceDesc: 'Price: High to Low',
    },
    product: {
      grade: 'Grade',
      origin: 'Origin',
      cutType: 'Cut',
      weight: 'Weight',
      per: 'per',
      outOfStock: 'Out of Stock',
      inStockBefore: 'In Stock (',
      inStockAfter: ')',
      about: 'About This Product',
      related: 'You May Also Like',
      addToCart: 'Add to Cart',
      badgeColdChain: 'Cold Chain Delivery',
      badgeHaccp: 'HACCP Certified',
      badgeVacuum: 'Vacuum Packed',
    },
    cart: {
      title: 'Cart',
      empty: 'Your cart is empty',
      shopNow: 'Shop Now',
      freeShippingBefore: '',
      freeShippingAfter: ' away from free shipping!',
      freeShippingReached: 'You qualify for free shipping!',
      subtotal: 'Subtotal',
      shippingNote: 'Shipping and taxes calculated at checkout.',
      checkout: 'Checkout',
      continueShopping: 'Continue Shopping',
    },
    footer: {
      tagline: 'Premium cuts from the finest farms, delivered directly to you.',
      shop: 'Shop',
      allProducts: 'All Products',
      wagyu: 'Wagyu',
      pork: 'Pork',
      chicken: 'Chicken',
      lamb: 'Lamb',
      support: 'Support',
      shipping: 'Shipping',
      returns: 'Returns & Exchange',
      faq: 'FAQ',
      privacy: 'Privacy Policy',
      terms: 'Terms of Use',
    },
    checkout: {
      orderComplete: 'Order Complete!',
      orderNumberPrefix: 'Order #',
      thankYou1: 'Thank you for your order! A confirmation email has been sent to ',
      thankYou2: '. Your items will be shipped soon.',
      continueShopping: 'Continue Shopping',
      emptyCart: 'Your cart is empty',
      backToShopping: 'Back to Shopping',
      title: 'Checkout',
      customerInfo: 'Customer Information',
      name: 'Full Name *',
      namePlaceholder: 'John Doe',
      email: 'Email Address *',
      emailPlaceholder: 'john@example.com',
      phone: 'Phone Number',
      phonePlaceholder: '+1 555-0000',
      shippingAddress: 'Shipping Address',
      address: 'Address *',
      addressPlaceholder: '123 Main St',
      city: 'City *',
      cityPlaceholder: 'Los Angeles',
      state: 'State / Province',
      postal: 'Postal Code *',
      postalPlaceholder: '90001',
      country: 'Country',
      notes: 'Notes (optional)',
      notesPlaceholder: 'Special instructions, preferred delivery time, etc...',
      payment: 'Payment Method',
      payCard: 'Credit / Debit Card',
      payCardDesc: 'Pay securely by card',
      payBank: 'Bank Transfer',
      payBankDesc: 'Transfer directly to our account',
      payCod: 'Cash on Delivery',
      payCodDesc: 'Pay upon delivery',
      cardPlaceholder: 'Card payment form will be integrated here',
      bankDetailsTitle: 'Bank Transfer Details:',
      bankName: 'Bank: First National Bank',
      bankAccount: 'Account: 123-456-7890',
      bankRef: 'Reference: Order number (provided after order)',
      errorRequired: 'Please fill in all required fields.',
      errorGeneral: 'An error occurred. Please try again.',
      orderSummary: 'Order Summary',
      quantityLabel: 'Qty: ',
      subtotal: 'Subtotal',
      shipping: 'Shipping',
      free: 'Free',
      tax: 'Tax (10%)',
      total: 'Total',
      placeOrder: 'Place Order',
      placing: 'Placing order...',
      secureBadge: 'Secure Checkout',
    },
    orders: {
      title: 'Order Tracking',
      desc: 'To check your order status, please contact us with your order number and the email used at checkout.',
      contact: 'Contact Support',
      continueShopping: 'Continue Shopping',
    },
  },
} as const

export type Dict = typeof dict.ja
