import { cookies } from 'next/headers'

export type Lang = 'ja' | 'en' | 'vi'

export async function getLang(): Promise<Lang> {
  const cookieStore = await cookies()
  const lang = cookieStore.get('lang')?.value
  return lang === 'en' || lang === 'vi' ? lang : 'ja'
}

export const dict = {
  ja: {
    nav: { home: 'ホーム', shop: 'ショップ' },
    hero: {
      eyebrow: '冷凍肉卸売業者',
      title1: '冷凍肉',
      title2: '大量仕入れ',
      title3: '安定供給',
      subtitle: 'レストラン、ホテル、食品事業者向けの信頼できる冷凍肉供給。一貫した品質、競争力のある大口価格、確かなコールドチェーン配送。',
      cta: '商品カタログを見る',
      marquee: ['冷凍', '大口注文', 'B2B', '卸売', '牛肉', '豚肉', '鶏肉', '冷凍供給', '信頼性', 'バルクカット', 'コールドチェーン', 'OISHI NIKU'],
    },
    home: {
      featuredEyebrow: '商品ラインナップ',
      featuredTitle: '取扱商品',
      featuredViewAll: 'すべて見る',
      featuredEmpty: 'おすすめ商品はまだありません',
      featuredEmptyDesc: '管理画面から商品を追加し、おすすめに設定してください。',
      featuredViewAllBtn: 'すべての商品を見る',
      faqEyebrow: '取引に関するお問い合わせ',
      faqTitle: 'よくある質問',
      b2bEyebrow: 'パートナーになる',
      b2bTitle: '取引口座を開設する',
      b2bDesc: 'レストラン、ホテル、食品卸業者の方へ — 卸売価格、NET-30 支払条件、専任アカウントマネージャーをご利用いただけます。',
      b2bPlaceholder: 'ビジネスメールアドレスを入力',
      b2bCta: '今すぐ申し込む',
      faqs: [
        { q: '最小注文数量はどのくらいですか？', a: '1商品あたり最小20kgからご注文いただけます。混載パレットの場合、最小注文合計は100kgです。200kg、500kg、1000kgの各基準で数量割引が自動適用されます。' },
        { q: '冷凍肉の梁包・配送方法は？', a: '全商品は真空パックの上、ドライアイス入りの断熱カートンで梁包されます。倉庫からお届け先まで完全なコールドチェーンを維持し、製品温度が-18℃を超えることはありません。' },
        { q: '商品はどのような認証を取得していますか？', a: 'サプライチェーン全体がHACCP認証を取得しており、全商品が国際食品安全基準を満たしています。ご要望に応じて、完全なトレーサビリティ証明書、ハラール認証、原産国証明書を提供できます。' },
        { q: 'レストランやホテル向けのカスタムカットは対応可能ですか？', a: 'はい。定期注文のB2Bクライアント様には、カスタムポーション加工、トリミング、ラベリングに対応しています。仕様要件についてはお気軽にお問い合わせください。' },
        { q: '支払い・クレジット条件はどうなっていますか？', a: '銀行振込をお受けしており、承認済み法人口座にはNET-30の支払い条件を提供しています。初回注文は前払いが必要です。取引口座の開設については営業チームまでお問い合わせください。' },
      ],
    },
    products: {
      eyebrow: '商品一覧',
      title: '全商品',
      countBefore: '',
      countAfter: '件の商品',
      notFound: '商品が見つかりません',
      notFoundDesc: 'フィルターまたは検索キーワードを変更してください。',
      allCategories: 'すべてのカテゴリー',
      sortNewest: '新着順',
      sortPopular: '人気順',
      sortPriceAsc: '価格: 安い順',
      sortPriceDesc: '価格: 高い順',
    },
    product: {
      grade: 'グレード',
      origin: '産地',
      cutType: '部位',
      weight: '重量',
      per: 'あたり',
      outOfStock: '在庫切れ',
      inStockBefore: '在庫あり（',
      inStockAfter: '点）',
      about: '商品について',
      related: 'こちらもおすすめ',
      addToCart: 'カートに追加',
      badgeColdChain: 'コールドチェーン配送',
      badgeHaccp: 'HACCP認証取得',
      badgeVacuum: '真空パック',
    },
    cart: {
      title: 'カート',
      empty: 'カートは空です',
      shopNow: '今すぐ購入',
      freeShippingBefore: 'あと ',
      freeShippingAfter: ' で送料無料！',
      freeShippingReached: '送料無料の対象です！',
      subtotal: '小計',
      shippingNote: '送料・税金はチェックアウト時に計算されます。',
      checkout: 'お会計',
      continueShopping: 'ショッピングを続ける',
    },
    footer: {
      tagline: '最高品質の農場から厳選した精肉。最良のカットを直接お届けします。',
      shop: 'ショップ',
      allProducts: '全商品',
      wagyu: '和牛',
      pork: '豚肉',
      chicken: '鶏肉',
      lamb: 'ラム肉',
      support: 'サポート',
      shipping: '配送情報',
      returns: '返品・交換',
      faq: 'よくある質問',
      privacy: 'プライバシーポリシー',
      terms: '利用規約',
    },
    checkout: {
      orderComplete: 'ご注文完了！',
      orderNumberPrefix: '注文番号 #',
      thankYou1: 'ご注文ありがとうございます！',
      thankYou2: ' に確認メールをお送りしました。商品は近日中に発送いたします。',
      continueShopping: 'ショッピングを続ける',
      emptyCart: 'カートは空です',
      backToShopping: 'ショッピングに戻る',
      title: 'お会計',
      customerInfo: 'お客様情報',
      name: '氏名 *',
      namePlaceholder: '山田 太郎',
      email: 'メールアドレス *',
      emailPlaceholder: 'taro@example.com',
      phone: '電話番号',
      phonePlaceholder: '090-0000-0000',
      shippingAddress: 'お届け先住所',
      address: '住所 *',
      addressPlaceholder: '東京都渋谷区1-2-3',
      city: '市区町村 *',
      cityPlaceholder: '渋谷区',
      state: '都道府県',
      postal: '郵便番号 *',
      postalPlaceholder: '150-0001',
      country: '国',
      notes: '備考（任意）',
      notesPlaceholder: '特別な指示、希望配達時間など...',
      payment: '支払い方法',
      payCard: 'クレジット / デビットカード',
      payCardDesc: 'カードで安全にお支払い',
      payBank: '銀行振込',
      payBankDesc: '直接口座にお振込みください',
      payCod: '代金引換',
      payCodDesc: '商品到着時にお支払い',
      cardPlaceholder: 'カード決済フォームはこちらに統合されます',
      bankDetailsTitle: '銀行振込の詳細：',
      bankName: '銀行: ファーストナショナル銀行',
      bankAccount: '口座番号: 123-456-7890',
      bankRef: '振込名義: ご注文番号（注文後にお知らせします）',
      errorRequired: '必須項目をすべて入力してください。',
      errorGeneral: 'エラーが発生しました。もう一度お試しください。',
      orderSummary: '注文内容',
      quantityLabel: '数量: ',
      subtotal: '小計',
      shipping: '送料',
      free: '無料',
      tax: '消費税（10%）',
      total: '合計',
      placeOrder: '注文する',
      placing: '注文中...',
      secureBadge: '安全なチェックアウト',
    },
    orders: {
      title: '注文の追跡',
      desc: '注文状況を確認するには、注文番号とご注文時に使用したメールアドレスをお知らせの上、お問い合わせください。',
      contact: 'サポートに連絡する',
      continueShopping: 'ショッピングを続ける',
    },
  },

  en: {
    nav: { home: 'Home', shop: 'Shop' },
    hero: {
      eyebrow: 'Frozen Meat Wholesaler',
      title1: 'Frozen',
      title2: 'Bulk Orders',
      title3: 'Stable Supply',
      subtitle: 'Reliable frozen meat supply for restaurants, hotels, and food businesses. Consistent quality, competitive bulk pricing, and dependable cold chain delivery.',
      cta: 'View Product Catalog',
      marquee: ['Frozen', 'Bulk Orders', 'B2B', 'Wholesale', 'Beef', 'Pork', 'Chicken', 'Cold Supply', 'Reliability', 'Bulk Cuts', 'Cold Chain', 'OISHI NIKU'],
    },
    home: {
      featuredEyebrow: 'Product Lineup',
      featuredTitle: 'Our Products',
      featuredViewAll: 'View All',
      featuredEmpty: 'No featured products yet',
      featuredEmptyDesc: 'Add products from the admin panel and mark them as featured.',
      featuredViewAllBtn: 'View All Products',
      faqEyebrow: 'Business Inquiries',
      faqTitle: 'FAQ',
      b2bEyebrow: 'Become a Partner',
      b2bTitle: 'Open a Trade Account',
      b2bDesc: 'For restaurants, hotels, and food distributors — enjoy wholesale pricing, NET-30 payment terms, and a dedicated account manager.',
      b2bPlaceholder: 'Enter your business email',
      b2bCta: 'Apply Now',
      faqs: [
        { q: 'What is the minimum order quantity?', a: 'Minimum 20kg per product. For mixed pallets, the minimum total order is 100kg. Volume discounts automatically apply at the 200kg, 500kg, and 1000kg thresholds.' },
        { q: 'How is frozen meat packaged and shipped?', a: 'All products are vacuum-packed and packaged in insulated cartons with dry ice. A complete cold chain is maintained from warehouse to delivery, and product temperature never exceeds -18°C.' },
        { q: 'What certifications do your products have?', a: 'Our entire supply chain is HACCP certified and all products meet international food safety standards. Upon request, we can provide full traceability certificates, halal certification, and certificates of origin.' },
        { q: 'Can you provide custom cuts for restaurants and hotels?', a: 'Yes. For B2B clients with regular orders, we offer custom portioning, trimming, and labeling. Please feel free to contact us regarding your specification requirements.' },
        { q: 'What are the payment and credit terms?', a: 'We accept bank transfers and offer NET-30 payment terms for approved corporate accounts. First orders require prepayment. Please contact our sales team to open a trade account.' },
      ],
    },
    products: {
      eyebrow: 'Products',
      title: 'All Products',
      countBefore: '',
      countAfter: ' products',
      notFound: 'No products found',
      notFoundDesc: 'Try changing the filters or search keywords.',
      allCategories: 'All Categories',
      sortNewest: 'Newest',
      sortPopular: 'Popular',
      sortPriceAsc: 'Price: Low to High',
      sortPriceDesc: 'Price: High to Low',
    },
    product: {
      grade: 'Grade',
      origin: 'Origin',
      cutType: 'Cut',
      weight: 'Weight',
      per: 'per',
      outOfStock: 'Out of Stock',
      inStockBefore: 'In Stock (',
      inStockAfter: ')',
      about: 'About This Product',
      related: 'You May Also Like',
      addToCart: 'Add to Cart',
      badgeColdChain: 'Cold Chain Delivery',
      badgeHaccp: 'HACCP Certified',
      badgeVacuum: 'Vacuum Packed',
    },
    cart: {
      title: 'Cart',
      empty: 'Your cart is empty',
      shopNow: 'Shop Now',
      freeShippingBefore: '',
      freeShippingAfter: ' away from free shipping!',
      freeShippingReached: 'You qualify for free shipping!',
      subtotal: 'Subtotal',
      shippingNote: 'Shipping and taxes calculated at checkout.',
      checkout: 'Checkout',
      continueShopping: 'Continue Shopping',
    },
    footer: {
      tagline: 'Premium cuts from the finest farms, delivered directly to you.',
      shop: 'Shop',
      allProducts: 'All Products',
      wagyu: 'Wagyu',
      pork: 'Pork',
      chicken: 'Chicken',
      lamb: 'Lamb',
      support: 'Support',
      shipping: 'Shipping',
      returns: 'Returns & Exchange',
      faq: 'FAQ',
      privacy: 'Privacy Policy',
      terms: 'Terms of Use',
    },
    checkout: {
      orderComplete: 'Order Complete!',
      orderNumberPrefix: 'Order #',
      thankYou1: 'Thank you for your order! A confirmation email has been sent to ',
      thankYou2: '. Your items will be shipped soon.',
      continueShopping: 'Continue Shopping',
      emptyCart: 'Your cart is empty',
      backToShopping: 'Back to Shopping',
      title: 'Checkout',
      customerInfo: 'Customer Information',
      name: 'Full Name *',
      namePlaceholder: 'John Doe',
      email: 'Email Address *',
      emailPlaceholder: 'john@example.com',
      phone: 'Phone Number',
      phonePlaceholder: '+1 555-0000',
      shippingAddress: 'Shipping Address',
      address: 'Address *',
      addressPlaceholder: '123 Main St',
      city: 'City *',
      cityPlaceholder: 'Los Angeles',
      state: 'State / Province',
      postal: 'Postal Code *',
      postalPlaceholder: '90001',
      country: 'Country',
      notes: 'Notes (optional)',
      notesPlaceholder: 'Special instructions, preferred delivery time, etc...',
      payment: 'Payment Method',
      payCard: 'Credit / Debit Card',
      payCardDesc: 'Pay securely by card',
      payBank: 'Bank Transfer',
      payBankDesc: 'Transfer directly to our account',
      payCod: 'Cash on Delivery',
      payCodDesc: 'Pay upon delivery',
      cardPlaceholder: 'Card payment form will be integrated here',
      bankDetailsTitle: 'Bank Transfer Details:',
      bankName: 'Bank: First National Bank',
      bankAccount: 'Account: 123-456-7890',
      bankRef: 'Reference: Order number (provided after order)',
      errorRequired: 'Please fill in all required fields.',
      errorGeneral: 'An error occurred. Please try again.',
      orderSummary: 'Order Summary',
      quantityLabel: 'Qty: ',
      subtotal: 'Subtotal',
      shipping: 'Shipping',
      free: 'Free',
      tax: 'Tax (10%)',
      total: 'Total',
      placeOrder: 'Place Order',
      placing: 'Placing order...',
      secureBadge: 'Secure Checkout',
    },
    orders: {
      title: 'Order Tracking',
      desc: 'To check your order status, please contact us with your order number and the email used at checkout.',
      contact: 'Contact Support',
      continueShopping: 'Continue Shopping',
    },
  },

  vi: {
    nav: { home: 'Trang Chủ', shop: 'Cửa Hàng' },
    hero: {
      eyebrow: 'Nhà Cung Cấp Thịt Đông Lạnh',
      title1: 'Thịt',
      title2: 'Đặt Số Lượng Lớn',
      title3: 'Cung Cấp Ổn Định',
      subtitle: 'Nguồn cung thịt đông lạnh đáng tin cậy cho nhà hàng, khách sạn và doanh nghiệp thực phẩm. Chất lượng nhất quán, giá sỉ cạnh tranh và giao hàng chuỗi lạnh đảm bảo.',
      cta: 'Xem Danh Mục Sản Phẩm',
      marquee: ['Đông Lạnh', 'Đặt Số Lượng Lớn', 'B2B', 'Bán Sỉ', 'Thịt Bò', 'Thịt Heo', 'Thịt Gà', 'Cung Cấp Lạnh', 'Tin Cậy', 'Cắt Sỉ', 'Chuỗi Lạnh', 'OISHI NIKU'],
    },
    home: {
      featuredEyebrow: 'Danh Mục Sản Phẩm',
      featuredTitle: 'Sản Phẩm',
      featuredViewAll: 'Xem Tất Cả',
      featuredEmpty: 'Chưa có sản phẩm nổi bật',
      featuredEmptyDesc: 'Thêm sản phẩm từ trang quản trị và đánh dấu là nổi bật.',
      featuredViewAllBtn: 'Xem Tất Cả Sản Phẩm',
      faqEyebrow: 'Thắc Mắc Kinh Doanh',
      faqTitle: 'Câu Hỏi Thường Gặp',
      b2bEyebrow: 'Trở Thành Đối Tác',
      b2bTitle: 'Mở Tài Khoản Giao Dịch',
      b2bDesc: 'Dành cho nhà hàng, khách sạn và nhà phân phối thực phẩm — hưởng giá bán sỉ, điều khoản thanh toán NET-30 và quản lý tài khoản chuyên trách.',
      b2bPlaceholder: 'Nhập email doanh nghiệp',
      b2bCta: 'Đăng Ký Ngay',
      faqs: [
        { q: 'Số lượng đặt hàng tối thiểu là bao nhiêu?', a: 'Tối thiểu 20kg mỗi sản phẩm. Đối với pallet hỗn hợp, tổng đơn hàng tối thiểu là 100kg. Chiết khấu số lượng tự động áp dụng ở mức 200kg, 500kg và 1000kg.' },
        { q: 'Thịt đông lạnh được đóng gói và vận chuyển như thế nào?', a: 'Tất cả sản phẩm được đóng gói chân không trong thùng cách nhiệt có đá khô. Duy trì chuỗi lạnh hoàn chỉnh từ kho đến điểm giao hàng, nhiệt độ sản phẩm không vượt quá -18°C.' },
        { q: 'Sản phẩm của bạn có những chứng nhận gì?', a: 'Toàn bộ chuỗi cung ứng được chứng nhận HACCP và tất cả sản phẩm đáp ứng tiêu chuẩn an toàn thực phẩm quốc tế. Theo yêu cầu, chúng tôi cung cấp chứng chỉ truy xuất nguồn gốc, chứng nhận halal và chứng nhận xuất xứ.' },
        { q: 'Có thể cung cấp các loại cắt tùy chỉnh cho nhà hàng và khách sạn không?', a: 'Có. Đối với khách hàng B2B có đơn hàng thường xuyên, chúng tôi cung cấp dịch vụ chia phần, cắt tỉa và dán nhãn tùy chỉnh. Vui lòng liên hệ để thảo luận về yêu cầu cụ thể.' },
        { q: 'Điều khoản thanh toán và tín dụng như thế nào?', a: 'Chúng tôi chấp nhận chuyển khoản ngân hàng và cung cấp điều khoản NET-30 cho tài khoản doanh nghiệp được phê duyệt. Đơn hàng đầu tiên yêu cầu thanh toán trước. Liên hệ đội bán hàng để mở tài khoản giao dịch.' },
      ],
    },
    products: {
      eyebrow: 'Sản Phẩm',
      title: 'Tất Cả Sản Phẩm',
      countBefore: '',
      countAfter: ' sản phẩm',
      notFound: 'Không tìm thấy sản phẩm',
      notFoundDesc: 'Thử thay đổi bộ lọc hoặc từ khóa tìm kiếm.',
      allCategories: 'Tất Cả Danh Mục',
      sortNewest: 'Mới Nhất',
      sortPopular: 'Phổ Biến',
      sortPriceAsc: 'Giá: Thấp đến Cao',
      sortPriceDesc: 'Giá: Cao đến Thấp',
    },
    product: {
      grade: 'Cấp Độ',
      origin: 'Xuất Xứ',
      cutType: 'Phần Cắt',
      weight: 'Trọng Lượng',
      per: 'mỗi',
      outOfStock: 'Hết Hàng',
      inStockBefore: 'Còn Hàng (',
      inStockAfter: ')',
      about: 'Về Sản Phẩm',
      related: 'Có Thể Bạn Cũng Thích',
      addToCart: 'Thêm Vào Giỏ',
      badgeColdChain: 'Vận Chuyển Chuỗi Lạnh',
      badgeHaccp: 'Chứng Nhận HACCP',
      badgeVacuum: 'Đóng Gói Chân Không',
    },
    cart: {
      title: 'Giỏ Hàng',
      empty: 'Giỏ hàng trống',
      shopNow: 'Mua Ngay',
      freeShippingBefore: 'Còn ',
      freeShippingAfter: ' để miễn phí vận chuyển!',
      freeShippingReached: 'Bạn được miễn phí vận chuyển!',
      subtotal: 'Tạm Tính',
      shippingNote: 'Phí vận chuyển và thuế tính khi thanh toán.',
      checkout: 'Thanh Toán',
      continueShopping: 'Tiếp Tục Mua Sắm',
    },
    footer: {
      tagline: 'Thịt cao cấp từ những trang trại tốt nhất, giao trực tiếp đến bạn.',
      shop: 'Cửa Hàng',
      allProducts: 'Tất Cả Sản Phẩm',
      wagyu: 'Wagyu',
      pork: 'Thịt Heo',
      chicken: 'Thịt Gà',
      lamb: 'Thịt Cừu',
      support: 'Hỗ Trợ',
      shipping: 'Thông Tin Giao Hàng',
      returns: 'Đổi Trả',
      faq: 'Câu Hỏi Thường Gặp',
      privacy: 'Chính Sách Bảo Mật',
      terms: 'Điều Khoản Sử Dụng',
    },
    checkout: {
      orderComplete: 'Đặt Hàng Thành Công!',
      orderNumberPrefix: 'Đơn Hàng #',
      thankYou1: 'Cảm ơn bạn đã đặt hàng! Email xác nhận đã được gửi đến ',
      thankYou2: '. Sản phẩm của bạn sẽ sớm được giao.',
      continueShopping: 'Tiếp Tục Mua Sắm',
      emptyCart: 'Giỏ hàng trống',
      backToShopping: 'Quay Lại Mua Sắm',
      title: 'Thanh Toán',
      customerInfo: 'Thông Tin Khách Hàng',
      name: 'Họ Và Tên *',
      namePlaceholder: 'Nguyễn Văn A',
      email: 'Địa Chỉ Email *',
      emailPlaceholder: 'nguyen@example.com',
      phone: 'Số Điện Thoại',
      phonePlaceholder: '0901-000-000',
      shippingAddress: 'Địa Chỉ Giao Hàng',
      address: 'Địa Chỉ *',
      addressPlaceholder: '123 Đường Lê Lợi, Q.1',
      city: 'Thành Phố *',
      cityPlaceholder: 'TP. Hồ Chí Minh',
      state: 'Tỉnh / Thành',
      postal: 'Mã Bưu Chính *',
      postalPlaceholder: '700000',
      country: 'Quốc Gia',
      notes: 'Ghi Chú (tùy chọn)',
      notesPlaceholder: 'Hướng dẫn đặc biệt, thời gian giao hàng mong muốn...',
      payment: 'Phương Thức Thanh Toán',
      payCard: 'Thẻ Tín Dụng / Ghi Nợ',
      payCardDesc: 'Thanh toán an toàn bằng thẻ',
      payBank: 'Chuyển Khoản Ngân Hàng',
      payBankDesc: 'Chuyển khoản trực tiếp vào tài khoản',
      payCod: 'Thanh Toán Khi Nhận Hàng',
      payCodDesc: 'Thanh toán khi nhận hàng',
      cardPlaceholder: 'Form thanh toán thẻ sẽ được tích hợp tại đây',
      bankDetailsTitle: 'Chi Tiết Chuyển Khoản:',
      bankName: 'Ngân Hàng: First National Bank',
      bankAccount: 'Tài Khoản: 123-456-7890',
      bankRef: 'Tham chiếu: Số đơn hàng (cung cấp sau khi đặt hàng)',
      errorRequired: 'Vui lòng điền vào tất cả các trường bắt buộc.',
      errorGeneral: 'Đã xảy ra lỗi. Vui lòng thử lại.',
      orderSummary: 'Tóm Tắt Đơn Hàng',
      quantityLabel: 'SL: ',
      subtotal: 'Tạm Tính',
      shipping: 'Phí Vận Chuyển',
      free: 'Miễn Phí',
      tax: 'Thuế (10%)',
      total: 'Tổng Cộng',
      placeOrder: 'Đặt Hàng',
      placing: 'Đang đặt hàng...',
      secureBadge: 'Thanh Toán An Toàn',
    },
    orders: {
      title: 'Theo Dõi Đơn Hàng',
      desc: 'Để kiểm tra tình trạng đơn hàng, vui lòng liên hệ chúng tôi với số đơn hàng và email đã dùng khi thanh toán.',
      contact: 'Liên Hệ Hỗ Trợ',
      continueShopping: 'Tiếp Tục Mua Sắm',
    },
  },
} as const

export type Dict = typeof dict.ja
