export type Lang = 'ja' | 'en'

export const dict = {
  ja: {
    nav: { home: 'ホーム', shop: 'ショップ', searchPlaceholder: '商品を検索…', cartLabel: 'カート', accountLabel: 'マイページ' },
    categoryNames: { beef: '牛肉', chicken: '鶏肉', pork: '豚肉' } as Record<string, string>,
    hero: {
      eyebrow: '冷凍肉卸売業者',
      title1: '冷凍肉',
      title2: '大量仕入れ',
      title3: '安定供給',
      subtitle: 'レストラン、ホテル、食品事業者向けの信頼できる冷凍肉供給。一貫した品質、競争力のある大口価格、確かなコールドチェーン配送。',
      cta: '商品カタログを見る',
      marquee: ['冷凍', '大口注文', 'B2B', '卸売', '牛肉', '豚肉', '鶏肉', '冷凍供給', '信頼性', 'バルクカット', 'コールドチェーン', 'OISHI NIKU'],
    },
    home: {
      bestSellersTitle: '🏆 人気商品',
      carouselSlides: [
        { icon: '🚚', title: '24〜28kgの箱で送料無料', sub: '24〜28kgまとめてご注文で全国送料無料', badge: '自動適用' },
        { icon: '🛡️', title: '食品衛生・安全を保証', sub: '国際食品衛生基準をクリアした高品質商品', badge: '品質保証' },
        { icon: '📦', title: '適切な包装・ラベル表示', sub: '規定に沿った包装・ラベリングを徹底実施', badge: '規定準拠' },
      ],
      featuredEyebrow: '商品ラインナップ',
      featuredTitle: '取扱商品',
      featuredViewAll: 'すべて見る',
      featuredEmpty: 'おすすめ商品はまだありません',
      featuredEmptyDesc: '管理画面から商品を追加し、おすすめに設定してください。',
      featuredViewAllBtn: 'すべての商品を見る',
      faqEyebrow: '取引に関するお問い合わせ',
      faqTitle: 'よくある質問',
      b2bEyebrow: 'パートナーになる',
      b2bTitle: '取引口座を開設する',
      b2bDesc: 'レストラン、ホテル、食品卸業者の方へ — 卸売価格、NET-30 支払条件、専任アカウントマネージャーをご利用いただけます。',
      b2bPlaceholder: 'ビジネスメールアドレスを入力',
      b2bCta: '今すぐ申し込む',
      faqs: [
        { q: '最小注文数量はどのくらいですか？', a: '1商品あたり最小20kgからご注文いただけます。混載パレットの場合、最小注文合計は100kgです。200kg、500kg、1000kgの各基準で数量割引が自動適用されます。' },
        { q: '冷凍肉の梁包・配送方法は？', a: '全商品は真空パックの上、ドライアイス入りの断熱カートンで梁包されます。倉庫からお届け先まで完全なコールドチェーンを維持し、製品温度が-18℃を超えることはありません。' },
        { q: '商品はどのような認証を取得していますか？', a: 'サプライチェーン全体がHACCP認証を取得しており、全商品が国際食品安全基準を満たしています。ご要望に応じて、完全なトレーサビリティ証明書、ハラール認証、原産国証明書を提供できます。' },
        { q: 'レストランやホテル向けのカスタムカットは対応可能ですか？', a: 'はい。定期注文のB2Bクライアント様には、カスタムポーション加工、トリミング、ラベリングに対応しています。仕様要件についてはお気軽にお問い合わせください。' },
        { q: '支払い・クレジット条件はどうなっていますか？', a: '銀行振込をお受けしており、承認済み法人口座にはNET-30の支払い条件を提供しています。初回注文は前払いが必要です。取引口座の開設については営業チームまでお問い合わせください。' },
      ],
    },
    products: {
      eyebrow: '商品一覧',
      title: '全商品',
      countBefore: '',
      countAfter: '件の商品',
      notFound: '商品が見つかりません',
      notFoundDesc: 'フィルターまたは検索キーワードを変更してください。',
      allCategories: 'すべてのカテゴリー',
      allProductsLink: 'すべての商品',
      sortNewest: '新着順',
      sortPopular: '人気順',
      sortPriceAsc: '価格: 安い順',
      sortPriceDesc: '価格: 高い順',
      searchPlaceholder: '商品を検索…',
      clearFilters: 'クリア',
      applyFilters: '適用',
      filterTitle: '絞り込み',
      searchLabel: 'キーワード検索',
      categoryLabel: 'カテゴリー',
      countSuffix: ' 件',
    },
    product: {
      grade: 'グレード',
      origin: '産地',
      cutType: '部位',
      weight: '重量',
      per: 'あたり',
      outOfStock: '在庫切れ',
      inStockBefore: '在庫あり（',
      inStockAfter: '点）',
      about: '商品について',
      related: 'こちらもおすすめ',
      addToCart: 'カートに追加',
      badgeColdChain: 'コールドチェーン配送',
      badgeHaccp: 'HACCP認証取得',
      badgeVacuum: '真空パック',
      soldOut: '完売',
      popular: '人気',
      featuredBadge: 'おすすめ',
      quickAdd: 'クイック追加',
      addedToCartSuffix: ' をカートに追加しました',
      taxIncluded: '税込',
    },
    cart: {
      title: 'カート',
      empty: 'カートは空です',
      addItemsPrompt: '商品を追加してください',
      shopNow: '今すぐ購入',
      freeShippingBefore: 'あと ',
      freeShippingAfter: ' で送料無料！',
      freeShippingReached: '送料無料の対象です！',
      subtotal: '小計',
      subtotalExclTax: '小計（税抜）',
      taxLine: '消費税（10%）',
      totalInclTax: '合計（税込・送料別）',
      shippingNote: '送料・税金はチェックアウト時に計算されます。',
      checkout: 'お会計',
      continueShopping: 'ショッピングを続ける',
    },
    footer: {
      tagline: '最高品質の農場から厳選した精肉。最良のカットを直接お届けします。',
      tagline2: 'プレミアム精肉をあなたのもとへ。',
      tags: ['全国配送', '翌日発送', '¥10,000以上送料無料'],
      shop: 'ショップ',
      allProducts: '全商品',
      beef: '牛肉',
      pork: '豚肉',
      chicken: '鶏肉',
      lamb: 'ラム肉',
      support: 'サポート',
      shipping: '配送情報',
      returns: '返品・交換',
      faq: 'よくある質問',
      privacy: 'プライバシーポリシー',
      terms: '利用規約',
    },
    checkout: {
      orderComplete: 'ご注文完了！',
      orderNumberPrefix: '注文番号 #',
      thankYou1: 'ご注文ありがとうございます！',
      thankYou2: ' に確認メールをお送りしました。商品は近日中に発送いたします。',
      continueShopping: 'ショッピングを続ける',
      emptyCart: 'カートは空です',
      backToShopping: 'ショッピングに戻る',
      title: '注文手続き',
      customerInfo: 'お客様情報',
      name: '氏名 *',
      namePlaceholder: '山田 太郎',
      email: 'メールアドレス *',
      emailPlaceholder: 'taro@example.com',
      phone: '電話番号',
      phonePlaceholder: '090-0000-0000',
      shippingAddress: 'お届け先住所',
      address: '住所 *',
      addressPlaceholder: '東京都渋谷区1-2-3',
      city: '市区町村 *',
      cityPlaceholder: '渋谷区',
      state: '都道府県',
      postal: '郵便番号 *',
      postalPlaceholder: '150-0001',
      country: '国',
      notes: '備考（任意）',
      notesPlaceholder: '特別な指示、希望配達時間など...',
      payment: '支払い方法',
      payCard: 'クレジット / デビットカード',
      payCardDesc: 'カードで安全にお支払い',
      payBank: '銀行振込',
      payBankDesc: '直接口座にお振込みください',
      payCod: '代金引換',
      payCodDesc: '商品到着時にお支払い',
      cardPlaceholder: 'カード決済フォームはこちらに統合されます',
      bankDetailsTitle: '銀行振込の詳細：',
      bankName: '銀行: ファーストナショナル銀行',
      bankAccount: '口座番号: 123-456-7890',
      bankRef: '振込名義: ご注文番号（注文後にお知らせします）',
      errorRequired: '必須項目をすべて入力してください。',
      errorGeneral: 'エラーが発生しました。もう一度お試しください。',
      orderSummary: '注文内容',
      quantityLabel: '数量: ',
      subtotal: '小計',
      shipping: '送料',
      free: '無料',
      tax: '消費税（10%）',
      total: '合計',
      placeOrder: '注文する',
      placing: '注文中...',
      secureBadge: '安全なチェックアウト',
      // new keys
      backToShop: 'ショップに戻る',
      shippingInfoSection: '配送先情報',
      nameLabel: '氏名',
      emailLabel: 'メールアドレス',
      phoneLabel: '電話番号',
      postalLabel: '郵便番号',
      autoFill: '自動入力',
      postalNotFound: '住所が見つかりませんでした。郵便番号（7桁）をご確認ください。',
      prefectureLabel: '都道府県',
      cityLabel: '市区町村',
      address1Label: '番地',
      address2Label: '建物名・部屋番号',
      address1Placeholder: '西新宿1-2-3',
      address2Placeholder: '新宿タワー 401号室',
      prefecturePlaceholder: '東京都',
      cityPlaceholder2: '新宿区',
      deliveryDateLabel: '配達希望日',
      deliveryTimeLabel: '配達希望時間帯',
      deliveryNote: '※ 配達日時はあくまで希望です。交通状況などにより前後する場合がございます。',
      remoteNotePrefix: '',
      remoteNoteSuffix: 'は最短2日後からご指定いただけます。',
      paymentSection: 'お支払い方法',
      codLabel: '代金引換',
      codFeeDescPre: '商品到着時にお支払い（手数料 ¥',
      codFeeDescPost: '）',
      bankLabel: '銀行振込',
      bankDesc: 'ご注文後に振込先をお知らせします。3営業日以内にお振込ください。',
      bankNoteTitle: '振込の際のお願い',
      bankNoteDesc: 'お振込の際は、振込名義欄に必ず「ご注文番号」をご記入ください。',
      bankNoteExample: 'のように入力してください。',
      bankYuchoTitle: 'ゆうちょ銀行からの振込',
      bankOtherTitle: '他の銀行からの振込',
      bankHolder: 'ド　ニュ　コオク　ヨン',
      bankYuchoNumber: '10340-72447231',
      bankOtherBranch: 'ゼロサンハチ (038)',
      bankOtherNumber: '72447231',
      bankOtherType: '普通',
      bankFanpageNote: '※ 振込完了後、振込明細の写真をファンページにお送りいただくと、確認次第すぐに発送手続きを行います。',
      qtyLabel: '数量: ',
      qtyTimes: ' × ',
      qtyExclTax: '（税抜）',
      subtotalExclTax: '小計（税抜）',
      taxLabel10: '消費税（10%）',
      shippingFeeLabel: '配送料',
      freeShippingProgressPre: 'あと¥',
      freeShippingProgressPost: '（税抜）で送料無料！',
      codFeeLabel: '代引き手数料',
      totalInclTax: '合計（税込）',
      processingLabel: '注文処理中…',
      placeOrderWith: '注文する — ¥',
      termsNote: 'ご注文をもって利用規約に同意したものとみなします。',
      thankYouTitle: 'ご注文ありがとうございます！',
      orderNumber: '注文番号',
      bankTransferTitle: 'お振込のご案内',
      bankTransferAmountPre: '3営業日以内に下記口座へ ',
      bankTransferAmountPost: ' をお振込ください。',
      bankRowBankName: '銀行名',
      bankRowHolder: '口座名義',
      bankRowAccountNum: '口座番号',
      bankRowBranchCode: '支店コード',
      bankRowTransferRef: '振込番号',
      bankRowAmount: '金額',
      bankRefNoticeTitle: '振込依頼人名のご記入について',
      bankRefNoticeBody: 'お振込の際は、振込名義欄に必ず',
      bankRefNoticePost: 'をご記入ください。',
      codPayTitle: '商品到着時にお支払いください。',
      codPayPre: '配達員に ',
      codPayPost: ' をお渡しください。',
      codFeeIncludedPre: '（代引き手数料 ¥',
      codFeeIncludedPost: ' 含む）',
      deliveryAddrLabel: 'お届け先：',
      deliveryDateConfirmLabel: '配達希望日：',
      shopBtn: '商品を見る',
      emptyCartDesc: '商品をカートに追加してからご注文ください。',
      errName: '氏名を入力してください。',
      errEmailRequired: 'メールアドレスを入力してください。',
      errEmailInvalid: '有効なメールアドレスを入力してください。',
      errPhoneShort: '電話番号は7桁以上で入力してください。',
      errPhoneLong: '電話番号が長すぎます。',
      errPostal: '郵便番号を入力してください。',
      errPrefecture: '都道府県を入力してください。',
      errAddress1: '番地を入力してください。',
      errDateRemote: '北海道・沖縄は2日後以降でご指定ください。',
      errDate: '1日後以降の日付を選択してください。',
      errDateRemoteLabel: '北海道・沖縄は2日後以降',
      errDateLabel: '1日後以降',
      deliveryTimeNone: '指定なし',
      deliveryTimeMorning: '午前（9:00〜12:00）',
      deliveryTimeAfternoon1: '午後①（12:00〜14:00）',
      deliveryTimeAfternoon2: '午後②（16:00〜18:00）',
      deliveryTimeEvening: '夕方（18:00〜20:00）',
      deliveryTimeNight: '夜間（19:00〜21:00）',
      dateLocale: 'ja-JP',
    },
    orders: {
      title: '注文の追跡',
      desc: '注文状況を確認するには、注文番号とご注文時に使用したメールアドレスをお知らせの上、お問い合わせください。',
      contact: 'サポートに連絡する',
      continueShopping: 'ショッピングを続ける',
    },
    auth: {
      loginTitle: 'ログイン',
      loginSubtitle: 'Oishi Niku アカウント',
      emailLabel: 'メールアドレス',
      passwordLabel: 'パスワード',
      loginBtn: 'ログイン',
      loggingIn: 'ログイン中...',
      noAccount: 'アカウントをお持ちでない方は',
      registerLink: '新規登録',
      registerTitle: '新規登録',
      registerSubtitle: 'Oishi Niku アカウントを作成',
      nameLabel: 'お名前',
      namePlaceholder: '山田 太郎',
      pwLabel: 'パスワード',
      pwPlaceholder: '8文字以上',
      confirmPwLabel: 'パスワード確認',
      confirmPwPlaceholder: 'もう一度入力',
      registerBtn: 'アカウント作成',
      registering: '登録中...',
      hasAccount: 'すでにアカウントをお持ちの方は',
      loginLink: 'ログイン',
      login: 'ログイン',
    },
    account: {
      orderHistory: '注文履歴',
      logout: 'ログアウト',
      recentOrders: '最近の注文',
      viewAll: 'すべて見る',
      noOrders: 'まだ注文がありません',
      shopNow: '商品を見る',
      orderPrefix: '注文 #',
      statusLabels: {
        pending:    '受付中',
        confirmed:  '確認済み',
        processing: '準備中',
        shipped:    '発送済み',
        delivered:  '配達完了',
        cancelled:  'キャンセル',
      },
      paymentLabels: {
        cod:  '代金引換',
        bank: '銀行振込',
        card: 'カード',
      },
      ordersTitle: '注文履歴',
      itemsSuffix: '点',
      shippingTo: 'お届け先:',
      dateLocale: 'ja-JP',
    },
  },

  en: {
    nav: { home: 'Home', shop: 'Shop', searchPlaceholder: 'Search products…', cartLabel: 'Cart', accountLabel: 'Account' },
    categoryNames: { beef: 'Beef', chicken: 'Chicken', pork: 'Pork' } as Record<string, string>,
    hero: {
      eyebrow: 'Frozen Meat Wholesaler',
      title1: 'Frozen',
      title2: 'Bulk Orders',
      title3: 'Stable Supply',
      subtitle: 'Reliable frozen meat supply for restaurants, hotels, and food businesses. Consistent quality, competitive bulk pricing, and dependable cold chain delivery.',
      cta: 'View Product Catalog',
      marquee: ['Frozen', 'Bulk Orders', 'B2B', 'Wholesale', 'Beef', 'Pork', 'Chicken', 'Cold Supply', 'Reliability', 'Bulk Cuts', 'Cold Chain', 'OISHI NIKU'],
    },
    home: {
      bestSellersTitle: '🏆 Best Sellers',
      carouselSlides: [
        { icon: '🚚', title: 'Free Shipping on 24-28kg Orders', sub: 'Orders from 24-28kg qualify for free nationwide delivery', badge: 'Free Ship' },
        { icon: '🛡️', title: 'Food Safety Guaranteed', sub: 'All products meet international food safety standards', badge: 'Certified' },
        { icon: '📦', title: 'Compliant Packaging & Labeling', sub: 'All packaging and labels meet regulatory requirements', badge: 'Compliant' },
      ],
      featuredEyebrow: 'Product Lineup',
      featuredTitle: 'Our Products',
      featuredViewAll: 'View All',
      featuredEmpty: 'No featured products yet',
      featuredEmptyDesc: 'Add products from the admin panel and mark them as featured.',
      featuredViewAllBtn: 'View All Products',
      faqEyebrow: 'Business Inquiries',
      faqTitle: 'FAQ',
      b2bEyebrow: 'Become a Partner',
      b2bTitle: 'Open a Trade Account',
      b2bDesc: 'For restaurants, hotels, and food distributors — enjoy wholesale pricing, NET-30 payment terms, and a dedicated account manager.',
      b2bPlaceholder: 'Enter your business email',
      b2bCta: 'Apply Now',
      faqs: [
        { q: 'What is the minimum order quantity?', a: 'Minimum 20kg per product. For mixed pallets, the minimum total order is 100kg. Volume discounts automatically apply at the 200kg, 500kg, and 1000kg thresholds.' },
        { q: 'How is frozen meat packaged and shipped?', a: 'All products are vacuum-packed and packaged in insulated cartons with dry ice. A complete cold chain is maintained from warehouse to delivery, and product temperature never exceeds -18°C.' },
        { q: 'What certifications do your products have?', a: 'Our entire supply chain is HACCP certified and all products meet international food safety standards. Upon request, we can provide full traceability certificates, halal certification, and certificates of origin.' },
        { q: 'Can you provide custom cuts for restaurants and hotels?', a: 'Yes. For B2B clients with regular orders, we offer custom portioning, trimming, and labeling. Please feel free to contact us regarding your specification requirements.' },
        { q: 'What are the payment and credit terms?', a: 'We accept bank transfers and offer NET-30 payment terms for approved corporate accounts. First orders require prepayment. Please contact our sales team to open a trade account.' },
      ],
    },
    products: {
      eyebrow: 'Products',
      title: 'All Products',
      countBefore: '',
      countAfter: ' products',
      notFound: 'No products found',
      notFoundDesc: 'Try changing the filters or search keywords.',
      allCategories: 'All Categories',
      allProductsLink: 'All Products',
      sortNewest: 'Newest',
      sortPopular: 'Popular',
      sortPriceAsc: 'Price: Low to High',
      sortPriceDesc: 'Price: High to Low',
      searchPlaceholder: 'Search products…',
      clearFilters: 'Clear',
      applyFilters: 'Apply',
      filterTitle: 'Filters',
      searchLabel: 'Search',
      categoryLabel: 'Category',
      countSuffix: ' results',
    },
    product: {
      grade: 'Grade',
      origin: 'Origin',
      cutType: 'Cut',
      weight: 'Weight',
      per: 'per',
      outOfStock: 'Out of Stock',
      inStockBefore: 'In Stock (',
      inStockAfter: ')',
      about: 'About This Product',
      related: 'You May Also Like',
      addToCart: 'Add to Cart',
      badgeColdChain: 'Cold Chain Delivery',
      badgeHaccp: 'HACCP Certified',
      badgeVacuum: 'Vacuum Packed',
      soldOut: 'Sold Out',
      popular: 'Popular',
      featuredBadge: 'Featured',
      quickAdd: 'Quick Add',
      addedToCartSuffix: ' added to cart',
      taxIncluded: 'incl. tax',
    },
    cart: {
      title: 'Cart',
      empty: 'Your cart is empty',
      addItemsPrompt: 'Add products to get started',
      shopNow: 'Shop Now',
      freeShippingBefore: '',
      freeShippingAfter: ' away from free shipping!',
      freeShippingReached: 'You qualify for free shipping!',
      subtotal: 'Subtotal',
      subtotalExclTax: 'Subtotal (excl. tax)',
      taxLine: 'Tax (10%)',
      totalInclTax: 'Total (incl. tax)',
      shippingNote: 'Shipping and taxes calculated at checkout.',
      checkout: 'Checkout',
      continueShopping: 'Continue Shopping',
    },
    footer: {
      tagline: 'Premium cuts from the finest farms, delivered directly to you.',
      tagline2: 'Premium meats, delivered to you.',
      tags: ['Nationwide', 'Next-Day Ship', 'Free Ship ¥10K+'],
      shop: 'Shop',
      allProducts: 'All Products',
      beef: 'Beef',
      pork: 'Pork',
      chicken: 'Chicken',
      lamb: 'Lamb',
      support: 'Support',
      shipping: 'Shipping',
      returns: 'Returns & Exchange',
      faq: 'FAQ',
      privacy: 'Privacy Policy',
      terms: 'Terms of Use',
    },
    checkout: {
      orderComplete: 'Order Complete!',
      orderNumberPrefix: 'Order #',
      thankYou1: 'Thank you for your order! A confirmation email has been sent to ',
      thankYou2: '. Your items will be shipped soon.',
      continueShopping: 'Continue Shopping',
      emptyCart: 'Your cart is empty',
      backToShopping: 'Back to Shopping',
      title: 'Checkout',
      customerInfo: 'Customer Information',
      name: 'Full Name *',
      namePlaceholder: 'John Doe',
      email: 'Email Address *',
      emailPlaceholder: 'john@example.com',
      phone: 'Phone Number',
      phonePlaceholder: '+1 555-0000',
      shippingAddress: 'Shipping Address',
      address: 'Address *',
      addressPlaceholder: '123 Main St',
      city: 'City *',
      cityPlaceholder: 'Los Angeles',
      state: 'State / Province',
      postal: 'Postal Code *',
      postalPlaceholder: '90001',
      country: 'Country',
      notes: 'Notes (optional)',
      notesPlaceholder: 'Special instructions, preferred delivery time, etc...',
      payment: 'Payment Method',
      payCard: 'Credit / Debit Card',
      payCardDesc: 'Pay securely by card',
      payBank: 'Bank Transfer',
      payBankDesc: 'Transfer directly to our account',
      payCod: 'Cash on Delivery',
      payCodDesc: 'Pay upon delivery',
      cardPlaceholder: 'Card payment form will be integrated here',
      bankDetailsTitle: 'Bank Transfer Details:',
      bankName: 'Bank: First National Bank',
      bankAccount: 'Account: 123-456-7890',
      bankRef: 'Reference: Order number (provided after order)',
      errorRequired: 'Please fill in all required fields.',
      errorGeneral: 'An error occurred. Please try again.',
      orderSummary: 'Order Summary',
      quantityLabel: 'Qty: ',
      subtotal: 'Subtotal',
      shipping: 'Shipping',
      free: 'Free',
      tax: 'Tax (10%)',
      total: 'Total',
      placeOrder: 'Place Order',
      placing: 'Placing order...',
      secureBadge: 'Secure Checkout',
      // new keys
      backToShop: 'Back to Shop',
      shippingInfoSection: 'Shipping Information',
      nameLabel: 'Full Name',
      emailLabel: 'Email Address',
      phoneLabel: 'Phone Number',
      postalLabel: 'Postal Code',
      autoFill: 'Auto-fill',
      postalNotFound: 'Address not found. Please check your postal code (7 digits).',
      prefectureLabel: 'Prefecture',
      cityLabel: 'City / Ward',
      address1Label: 'Street Address',
      address2Label: 'Building / Room',
      address1Placeholder: '1-2-3 Main Street',
      address2Placeholder: 'Tower A, Room 401',
      prefecturePlaceholder: 'Tokyo',
      cityPlaceholder2: 'Shinjuku',
      deliveryDateLabel: 'Preferred Delivery Date',
      deliveryTimeLabel: 'Preferred Time Slot',
      deliveryNote: '※ Delivery times are estimates and may vary due to traffic or other conditions.',
      remoteNotePrefix: '',
      remoteNoteSuffix: ' requires minimum 2 days for delivery.',
      paymentSection: 'Payment Method',
      codLabel: 'Cash on Delivery',
      codFeeDescPre: 'Pay upon delivery (¥',
      codFeeDescPost: ' handling fee)',
      bankLabel: 'Bank Transfer',
      bankDesc: 'Bank details will be provided after your order. Please transfer within 3 business days.',
      bankNoteTitle: 'Bank Transfer Note',
      bankNoteDesc: 'Please include your order number as the payment reference.',
      bankNoteExample: 'for example.',
      bankYuchoTitle: 'Transfer from Yucho Bank',
      bankOtherTitle: 'Transfer from Other Banks',
      bankHolder: 'DO NHU QUOC DUNG',
      bankYuchoNumber: '10340-72447231',
      bankOtherBranch: 'Zerosanpachi (038)',
      bankOtherNumber: '72447231',
      bankOtherType: 'Savings (普通)',
      bankFanpageNote: '※ After transferring, please send a photo of your receipt to our fanpage so we can confirm your payment and process your order right away.',
      qtyLabel: 'Qty: ',
      qtyTimes: ' × ',
      qtyExclTax: ' (excl. tax)',
      subtotalExclTax: 'Subtotal (excl. tax)',
      taxLabel10: 'Consumption Tax (10%)',
      shippingFeeLabel: 'Shipping',
      freeShippingProgressPre: '¥',
      freeShippingProgressPost: ' (excl. tax) away from free shipping!',
      codFeeLabel: 'COD Handling Fee',
      totalInclTax: 'Total (incl. tax)',
      processingLabel: 'Processing...',
      placeOrderWith: 'Place Order — ¥',
      termsNote: 'By placing your order, you agree to our Terms of Service.',
      thankYouTitle: 'Thank you for your order!',
      orderNumber: 'Order Number',
      bankTransferTitle: 'Bank Transfer Instructions',
      bankTransferAmountPre: 'Please transfer ',
      bankTransferAmountPost: ' within 3 business days.',
      bankRowBankName: 'Bank Name',
      bankRowHolder: 'Account Holder',
      bankRowAccountNum: 'Account Number',
      bankRowBranchCode: 'Branch Code',
      bankRowTransferRef: 'Transfer Reference',
      bankRowAmount: 'Amount',
      bankRefNoticeTitle: 'Payment Reference Instructions',
      bankRefNoticeBody: 'Please include',
      bankRefNoticePost: 'as the transfer reference.',
      codPayTitle: 'Please pay upon delivery.',
      codPayPre: 'Hand ',
      codPayPost: ' to the delivery driver.',
      codFeeIncludedPre: '(includes ¥',
      codFeeIncludedPost: ' COD fee)',
      deliveryAddrLabel: 'Delivery address:',
      deliveryDateConfirmLabel: 'Requested date:',
      shopBtn: 'Browse Products',
      emptyCartDesc: 'Please add items to your cart before checkout.',
      errName: 'Please enter your name.',
      errEmailRequired: 'Please enter your email address.',
      errEmailInvalid: 'Please enter a valid email address.',
      errPhoneShort: 'Phone number must be at least 7 digits.',
      errPhoneLong: 'Phone number is too long.',
      errPostal: 'Please enter your postal code.',
      errPrefecture: 'Please enter your prefecture / state.',
      errAddress1: 'Please enter your street address.',
      errDateRemote: 'Hokkaido/Okinawa requires minimum 2 days ahead.',
      errDate: 'Please select a date at least 1 day ahead.',
      errDateRemoteLabel: 'Hokkaido/Okinawa: min. 2 days ahead',
      errDateLabel: 'min. 1 day ahead',
      deliveryTimeNone: 'No preference',
      deliveryTimeMorning: 'Morning (9:00–12:00)',
      deliveryTimeAfternoon1: 'Early Afternoon (12:00–14:00)',
      deliveryTimeAfternoon2: 'Late Afternoon (16:00–18:00)',
      deliveryTimeEvening: 'Evening (18:00–20:00)',
      deliveryTimeNight: 'Night (19:00–21:00)',
      dateLocale: 'en-US',
    },
    orders: {
      title: 'Order Tracking',
      desc: 'To check your order status, please contact us with your order number and the email used at checkout.',
      contact: 'Contact Support',
      continueShopping: 'Continue Shopping',
    },
    auth: {
      loginTitle: 'Login',
      loginSubtitle: 'Oishi Niku Account',
      emailLabel: 'Email Address',
      passwordLabel: 'Password',
      loginBtn: 'Login',
      loggingIn: 'Logging in...',
      noAccount: "Don't have an account?",
      registerLink: 'Sign Up',
      registerTitle: 'Sign Up',
      registerSubtitle: 'Create your Oishi Niku account',
      nameLabel: 'Full Name',
      namePlaceholder: 'John Doe',
      pwLabel: 'Password',
      pwPlaceholder: 'Min. 8 characters',
      confirmPwLabel: 'Confirm Password',
      confirmPwPlaceholder: 'Repeat password',
      registerBtn: 'Create Account',
      registering: 'Creating account...',
      hasAccount: 'Already have an account?',
      loginLink: 'Login',
      login: 'Login',
    },
    account: {
      orderHistory: 'Order History',
      logout: 'Logout',
      recentOrders: 'Recent Orders',
      viewAll: 'View All',
      noOrders: 'No orders yet',
      shopNow: 'Shop Now',
      orderPrefix: 'Order #',
      statusLabels: {
        pending:    'Pending',
        confirmed:  'Confirmed',
        processing: 'Processing',
        shipped:    'Shipped',
        delivered:  'Delivered',
        cancelled:  'Cancelled',
      },
      paymentLabels: {
        cod:  'Cash on Delivery',
        bank: 'Bank Transfer',
        card: 'Card',
      },
      ordersTitle: 'Order History',
      itemsSuffix: ' items',
      shippingTo: 'Ship to:',
      dateLocale: 'en-US',
    },
  },
} as const

export type Dict = typeof dict.ja
